# Generated by Django 4.2 on 2023-05-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_trip', models.DateField()),
                ('time_of_trip', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('dosage', models.IntegerField()),
                ('dosage_units', models.CharField(default='mg', max_length=20)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripJournal.substance')),
            ],
        ),
    ]
