# Generated by Django 4.2 on 2023-05-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripJournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreport',
            name='date_of_trip',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
