# Generated by Django 4.2 on 2023-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripJournal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripreport',
            name='date_of_trip',
        ),
        migrations.RemoveField(
            model_name='tripreport',
            name='time_of_trip',
        ),
        migrations.AddField(
            model_name='tripreport',
            name='datetime_of_trip',
            field=models.DateTimeField(null=True),
        ),
    ]
