# Generated by Django 4.2 on 2023-05-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='dosage_units',
            field=models.CharField(default='mg', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='date_of_trip',
            field=models.DateTimeField(),
        ),
    ]
